name: ntfy
version: 1.3.0
slug: ntfy
description: Self-hosted pub-sub notification service (ntfy.sh)
url: https://github.com/pol4rfuchs/ha-apps
image: ghcr.io/pol4rfuchs/ntfy-ha-app
arch:
  - aarch64
  - amd64
init: false
panel_icon: mdi:bell-badge
panel_title: ntfy
webui: http://[HOST]:[PORT:4280]/
map:
  - backup:rw
ports:
  4280/tcp: 4280
ports_description:
  4280/tcp: ntfy Web UI & API
options:
  log_level: INFO
  base_url: ''
  behind_proxy: false
  auth_default_access: deny-all
  enable_signup: true
  enable_login: true
  enable_reservations: true
  cache_duration: 12h
  attachment_total_size_limit: 5G
  attachment_file_size_limit: 15M
  attachment_expiry_duration: 3h
  visitor_attachment_total_size_limit: 1G
  visitor_attachment_daily_bandwidth_limit: 5G
  keepalive_interval: 45s
  manager_interval: 3m
  visitor_request_limit_burst: 1000
  visitor_request_limit_replenish: 1s
  visitor_message_daily_limit: 1000000
  message_size_limit: '4096'
  upstream_base_url: ''
  admin_username: ''
  admin_password: ''
schema:
  log_level: list(TRACE|DEBUG|INFO|WARN|ERROR)
  base_url: str?
  behind_proxy: bool
  auth_default_access: list(deny-all|read-write|write-only|read-only)
  enable_signup: bool
  enable_login: bool
  enable_reservations: bool
  cache_duration: str
  attachment_total_size_limit: str
  attachment_file_size_limit: str
  attachment_expiry_duration: str
  visitor_attachment_total_size_limit: str
  visitor_attachment_daily_bandwidth_limit: str
  keepalive_interval: str
  manager_interval: str
  visitor_request_limit_burst: int
  visitor_request_limit_replenish: str
  visitor_message_daily_limit: int
  message_size_limit: str
  upstream_base_url: str?
  admin_username: str?
  admin_password: password?
