#!/usr/bin/with-contenv bashio
# ==============================================================================
# Home Assistant Add-on: ntfy
# ==============================================================================

readonly CONFIG_FILE="/etc/ntfy/server.yml"
readonly AUTH_FILE="/data/ntfy/user.db"
readonly HA_TOKEN_FILE="/data/ntfy/ha_token.txt"  # Fix 1: persisted HA token

bashio::log.info "Starting ntfy add-on …"

LOG_LEVEL=$(bashio::config 'log_level' 'INFO')
BASE_URL=$(bashio::config 'base_url' '')
BEHIND_PROXY=$(bashio::config 'behind_proxy' 'false')
AUTH_DEFAULT_ACCESS=$(bashio::config 'auth_default_access' 'deny-all')
ENABLE_SIGNUP=$(bashio::config 'enable_signup' 'true')
ENABLE_LOGIN=$(bashio::config 'enable_login' 'true')
ENABLE_RESERVATIONS=$(bashio::config 'enable_reservations' 'true')
CACHE_DURATION=$(bashio::config 'cache_duration' '12h')
ATTACHMENT_TOTAL=$(bashio::config 'attachment_total_size_limit' '5G')
ATTACHMENT_FILE=$(bashio::config 'attachment_file_size_limit' '15M')
ATTACHMENT_EXPIRY=$(bashio::config 'attachment_expiry_duration' '3h')
VISITOR_ATTACHMENT_TOTAL=$(bashio::config 'visitor_attachment_total_size_limit' '1G')
VISITOR_ATTACHMENT_BANDWIDTH=$(bashio::config 'visitor_attachment_daily_bandwidth_limit' '5G')
KEEPALIVE=$(bashio::config 'keepalive_interval' '45s')
MANAGER=$(bashio::config 'manager_interval' '3m')
VISITOR_REQUEST_LIMIT_BURST=$(bashio::config 'visitor_request_limit_burst' '1000')
VISITOR_REQUEST_LIMIT_REPLENISH=$(bashio::config 'visitor_request_limit_replenish' '1s')
VISITOR_MESSAGE_DAILY_LIMIT=$(bashio::config 'visitor_message_daily_limit' '0')
MESSAGE_SIZE_LIMIT=$(bashio::config 'message_size_limit' '4096')
UPSTREAM_URL=$(bashio::config 'upstream_base_url' '')
ADMIN_USER=$(bashio::config 'admin_username' '')
ADMIN_PASS=$(bashio::config 'admin_password' '')

mkdir -p /data/ntfy/cache /data/ntfy/attachments

bashio::log.info "Generating configuration …"
bashio::log.info "enable-reservations: ${ENABLE_RESERVATIONS}"
bashio::log.info "visitor-request-limit: burst=${VISITOR_REQUEST_LIMIT_BURST} replenish=${VISITOR_REQUEST_LIMIT_REPLENISH}"

cat > "${CONFIG_FILE}" <<EOF
# ntfy server.yml — auto-generated by HA add-on

listen-http: ":4280"

log-level: ${LOG_LEVEL}
log-format: text

behind-proxy: ${BEHIND_PROXY}

cache-file: /data/ntfy/cache/cache.db
cache-duration: "${CACHE_DURATION}"
cache-startup-queries: "pragma journal_mode(WAL); pragma synchronous(NORMAL);"

auth-file: ${AUTH_FILE}
auth-default-access: "${AUTH_DEFAULT_ACCESS}"

enable-signup: ${ENABLE_SIGNUP}
enable-login: ${ENABLE_LOGIN}
enable-reservations: ${ENABLE_RESERVATIONS}

keepalive-interval: "${KEEPALIVE}"
manager-interval: "${MANAGER}"

visitor-request-limit-burst: ${VISITOR_REQUEST_LIMIT_BURST}
visitor-request-limit-replenish: "${VISITOR_REQUEST_LIMIT_REPLENISH}"
visitor-message-daily-limit: ${VISITOR_MESSAGE_DAILY_LIMIT}

message-size-limit: "${MESSAGE_SIZE_LIMIT}"

# CORS: allow cross-origin API access (e.g. for ntfy_manager or other clients)
access-control-allow-origin: "*"
EOF

# base-url + attachments (both required together)
if bashio::config.has_value 'base_url' && [ -n "${BASE_URL}" ]; then
    bashio::log.info "base-url: ${BASE_URL}"
    cat >> "${CONFIG_FILE}" <<EOF

base-url: "${BASE_URL}"
attachment-cache-dir: /data/ntfy/attachments
attachment-total-size-limit: "${ATTACHMENT_TOTAL}"
attachment-file-size-limit: "${ATTACHMENT_FILE}"
attachment-expiry-duration: "${ATTACHMENT_EXPIRY}"
visitor-attachment-total-size-limit: "${VISITOR_ATTACHMENT_TOTAL}"
visitor-attachment-daily-bandwidth-limit: "${VISITOR_ATTACHMENT_BANDWIDTH}"
EOF
    bashio::log.info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.info " UnifiedPush / Matrix Push Gateway aktiv:"
    bashio::log.info "   ${BASE_URL}/_matrix/push/v1/notify"
    bashio::log.info " Element Android → Einstellungen → Benachrichtigungen"
    bashio::log.info "   → UnifiedPush → ntfy als Distributor wählen"
    bashio::log.info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
else
    bashio::log.info "No base-url set — local mode, attachments disabled"
    bashio::log.warning "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    bashio::log.warning " UnifiedPush / Matrix Push Gateway NICHT verfügbar!"
    bashio::log.warning " Grund: base_url ist nicht gesetzt."
    bashio::log.warning " → base_url in der Add-on Konfiguration setzen,"
    bashio::log.warning "   z.B.: https://ntfy.deine-domain.tld"
    bashio::log.warning "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
fi

# upstream-url (iOS push)
if bashio::config.has_value 'upstream_base_url' && [ -n "${UPSTREAM_URL}" ]; then
    bashio::log.info "upstream-base-url: ${UPSTREAM_URL}"
    echo "upstream-base-url: \"${UPSTREAM_URL}\"" >> "${CONFIG_FILE}"
fi

if bashio::debug; then
    bashio::log.debug "=== server.yml ==="
    cat "${CONFIG_FILE}"
    bashio::log.debug "=================="
fi

# ---------------------------------------------------------------------------
# Create admin users via ntfy CLI (NTFY_AUTH_FILE env var, no --config flag)
# Fix 4: NTFY_PASSWORD env var used throughout — zero interactive prompts
# ---------------------------------------------------------------------------
create_admin() {
    local username="$1"
    local password="$2"
    if [ -z "${username}" ] || [ -z "${password}" ]; then
        return
    fi
    if NTFY_AUTH_FILE="${AUTH_FILE}" ntfy user list </dev/null 2>/dev/null | grep -q "^user ${username}"; then
        bashio::log.info "Admin user '${username}' already exists — syncing password + role"
        NTFY_AUTH_FILE="${AUTH_FILE}" NTFY_PASSWORD="${password}" \
            ntfy user change-pass "${username}" </dev/null 2>/dev/null || true
    else
        bashio::log.info "Creating admin user '${username}' …"
        NTFY_AUTH_FILE="${AUTH_FILE}" NTFY_PASSWORD="${password}" \
            ntfy user add --role=admin "${username}" </dev/null 2>/dev/null || true
    fi
    NTFY_AUTH_FILE="${AUTH_FILE}" \
        ntfy user change-role "${username}" admin </dev/null 2>/dev/null || true
    bashio::log.info "Admin user '${username}' ready"
}

# ---------------------------------------------------------------------------
# Ensure admin user has a tier (required for /v1/account/reservation)
# Must run before provision_ha_token so the user is fully set up first.
# ---------------------------------------------------------------------------
provision_admin_tier() {
    local username="$1"
    [ -z "${username}" ] && return

    # Create tier if it doesn't exist yet
    if ! NTFY_AUTH_FILE="${AUTH_FILE}" ntfy tier list </dev/null 2>/dev/null | grep -q "^tier admin"; then
        bashio::log.info "Creating 'admin' tier …"
        NTFY_AUTH_FILE="${AUTH_FILE}" ntfy tier add \
            --message-limit=0 \
            --message-expiry-duration=8760h \
            --email-limit=0 \
            --reservation-limit=100 \
            --attachment-file-size-limit=100M \
            --attachment-total-size-limit=10G \
            admin </dev/null 2>/dev/null || true
    fi

    # Assign tier to admin user
    bashio::log.info "Assigning 'admin' tier to '${username}' …"
    NTFY_AUTH_FILE="${AUTH_FILE}" \
        ntfy user change-tier "${username}" admin </dev/null 2>/dev/null || true
}

# ---------------------------------------------------------------------------
# Fix 1: Token auto-provisioning
# Creates one persistent HA integration token at first startup.
# Token is written to /data/ntfy/ha_token.txt (survives restarts + backups).
# On subsequent starts the file already exists — no duplicate token created.
# ---------------------------------------------------------------------------
provision_ha_token() {
    local username="$1"

    # Token already exists — nothing to do regardless of username
    if [ -f "${HA_TOKEN_FILE}" ]; then
        local existing
        existing=$(cat "${HA_TOKEN_FILE}")
        bashio::log.info "HA token already provisioned → ${existing:0:16}…"
        return
    fi

    # First run — need username to create token
    if [ -z "${username}" ]; then
        bashio::log.info "Token auto-provisioning skipped — set admin_username in Configuration to enable"
        return
    fi

    bashio::log.info "Provisioning HA integration token for '${username}' …"
    local token_output
    local token_rc
    token_output=$(NTFY_AUTH_FILE="${AUTH_FILE}" \
        timeout 15 ntfy token add --label="Home Assistant" "${username}" </dev/null 2>&1)
    token_rc=$?

    if [ "${token_rc}" -eq 124 ]; then
        bashio::log.warning "Token provisioning timed out after 15s — skipping for now."
        bashio::log.warning "Run manually: ntfy_token ${username} 'Home Assistant'"
        return
    fi

    # ntfy token add output format: "token tk_XXXX (label) expires never"
    local token
    token=$(printf '%s' "${token_output}" | grep -oE 'tk_[A-Za-z0-9]+' | head -1)

    if [ -n "${token}" ]; then
        printf '%s\n' "${token}" > "${HA_TOKEN_FILE}"
        chmod 600 "${HA_TOKEN_FILE}"
        bashio::log.info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
        bashio::log.info " HA integration token created:"
        bashio::log.info " ${token}"
        bashio::log.info " Saved to: ${HA_TOKEN_FILE}"
        bashio::log.info " Use this in secrets.yaml:"
        bashio::log.info "   ntfy_token: ${token}"
        bashio::log.info "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    else
        bashio::log.warning "Token provisioning failed — output: ${token_output}"
        bashio::log.warning "Run manually: ntfy_token ${username} 'Home Assistant'"
    fi
}

# ---------------------------------------------------------------------------
# Execution order: user → tier → token
# ---------------------------------------------------------------------------
create_admin "${ADMIN_USER}" "${ADMIN_PASS}"
provision_admin_tier "${ADMIN_USER}"
provision_ha_token "${ADMIN_USER}"

bashio::log.info "Starting ntfy → http://homeassistant.local:4280"
exec ntfy serve --config="${CONFIG_FILE}" 2>&1
