#!/bin/bash
# ha-init.sh — Home Assistant ↔ Nextcloud bridge
# Runs before the official nextcloud /entrypoint.sh.
# Reads /data/options.json, configures NC env vars and PHP settings,
# sets up persistent data layout, then execs the upstream entrypoint.
set -euo pipefail

# ── Helpers ───────────────────────────────────────────────────────────────────
OPTIONS=/data/options.json

opt_str() {
    local key="$1" default="${2:-}"
    python3 -c "import json,sys; d=json.load(open('${OPTIONS}')); print(d.get('${key}','${default}'))" 2>/dev/null || echo "${default}"
}

opt_int() {
    local key="$1" default="${2:-0}"
    python3 -c "import json,sys; d=json.load(open('${OPTIONS}')); print(int(d.get('${key}',${default})))" 2>/dev/null || echo "${default}"
}

log() { echo "[ha-init] $*"; }

# ── Read HA options ───────────────────────────────────────────────────────────
ADMIN_USER=$(opt_str admin_user "admin")
ADMIN_PASS=$(opt_str admin_password "")
TRUSTED_DOMAINS=$(opt_str trusted_domains "")
DB_TYPE=$(opt_str db_type "mysql")
DB_HOST=$(opt_str db_host "core-mariadb")
DB_PORT=$(opt_int db_port 3306)
DB_NAME=$(opt_str db_name "nextcloud")
DB_USER=$(opt_str db_user "nextcloud")
DB_PASS=$(opt_str db_password "")
PHP_MEM=$(opt_str php_memory_limit "512M")
MAX_UPLOAD=$(opt_str max_upload_size "16G")
MAX_EXEC=$(opt_int max_execution_time 3600)
LOG_LEVEL=$(opt_str log_level "info")

# Nextcloud's config.php only knows a numeric loglevel (0=Debug .. 4=Fatal).
# Map the HA-side list(debug|info|warning|error|fatal) option onto it; the
# actual value is applied via occ in the docker-entrypoint-hooks.d scripts
# below, since config.php doesn't exist yet on first boot at this point.
case "${LOG_LEVEL}" in
  debug)   NC_LOG_LEVEL_NUM=0 ;;
  info)    NC_LOG_LEVEL_NUM=1 ;;
  warning) NC_LOG_LEVEL_NUM=2 ;;
  error)   NC_LOG_LEVEL_NUM=3 ;;
  fatal)   NC_LOG_LEVEL_NUM=4 ;;
  *)       NC_LOG_LEVEL_NUM=1 ;;
esac
export NC_LOG_LEVEL_NUM
log "Log level: ${LOG_LEVEL} (Nextcloud loglevel=${NC_LOG_LEVEL_NUM})"

# ── Persistent data layout ────────────────────────────────────────────────────
# HA mounts /data (add-on persistent storage).
# Layout:
#   /data/nextcloud/data   → NC user files (NEXTCLOUD_DATA_DIR)
#   /data/nextcloud/html   → NC app code + config.php (symlinked from /var/www/html)
#
# On first boot html/ is empty — the official NC entrypoint installs NC there.
# On subsequent boots the existing installation is reused.

NC_BASE=/data/nextcloud
mkdir -p "${NC_BASE}/data" "${NC_BASE}/html"

# Symlink /var/www/html → /data/nextcloud/html so NC installation persists
# across container image updates (only triggered when NC version changes).
if [[ ! -L /var/www/html ]]; then
    log "Relinking /var/www/html → ${NC_BASE}/html"
    # Copy existing image content on first boot so NC has its base files
    if [[ -z "$(ls -A "${NC_BASE}/html" 2>/dev/null)" ]]; then
        log "Copying NC base files into persistent volume (first boot)…"
        cp -a /var/www/html/. "${NC_BASE}/html/"
    fi
    rm -rf /var/www/html
    ln -s "${NC_BASE}/html" /var/www/html
fi

chown -R www-data:www-data "${NC_BASE}"

# ── Export Nextcloud env vars (used by official /entrypoint.sh) ───────────────
export NEXTCLOUD_ADMIN_USER="${ADMIN_USER}"
export NEXTCLOUD_ADMIN_PASSWORD="${ADMIN_PASS}"
export NEXTCLOUD_DATA_DIR="${NC_BASE}/data"

# Trusted domains: space-separated string → NC env var
# The official NC entrypoint splits on spaces for NEXTCLOUD_TRUSTED_DOMAINS.
if [[ -n "${TRUSTED_DOMAINS}" ]]; then
    export NEXTCLOUD_TRUSTED_DOMAINS="${TRUSTED_DOMAINS}"
fi

# ── Database ──────────────────────────────────────────────────────────────────
case "${DB_TYPE}" in
  mysql)
    log "DB: MariaDB @ ${DB_HOST}:${DB_PORT} / ${DB_NAME}"
    export MYSQL_HOST="${DB_HOST}:${DB_PORT}"
    export MYSQL_DATABASE="${DB_NAME}"
    export MYSQL_USER="${DB_USER}"
    export MYSQL_PASSWORD="${DB_PASS}"
    ;;
  pgsql)
    log "DB: PostgreSQL @ ${DB_HOST}:${DB_PORT} / ${DB_NAME}"
    export POSTGRES_HOST="${DB_HOST}"
    export POSTGRES_PORT="${DB_PORT}"
    export POSTGRES_DB="${DB_NAME}"
    export POSTGRES_USER="${DB_USER}"
    export POSTGRES_PASSWORD="${DB_PASS}"
    ;;
  sqlite)
    log "DB: SQLite (not recommended for production)"
    ;;
  *)
    log "Unknown db_type '${DB_TYPE}', falling back to sqlite"
    ;;
esac

# ── PHP runtime overrides ─────────────────────────────────────────────────────
PHP_INI=/usr/local/etc/php/conf.d/ha-nextcloud.ini
log "Writing PHP config: memory=${PHP_MEM}, upload=${MAX_UPLOAD}, exec=${MAX_EXEC}s"
cat > "${PHP_INI}" << EOF
; Generated by ha-init.sh — do not edit manually
memory_limit = ${PHP_MEM}
upload_max_filesize = ${MAX_UPLOAD}
post_max_size = ${MAX_UPLOAD}
max_execution_time = ${MAX_EXEC}
max_input_time = ${MAX_EXEC}
output_buffering = Off
EOF

# ── Redis socket (optional — enable if redis addon is running) ────────────────
# Uncomment if you add a redis option to config.yaml:
# export REDIS_HOST=/var/run/redis/redis.sock

log "Handing off to official Nextcloud entrypoint…"
exec /entrypoint.sh "$@"
