name: 10 Hassfest

on:
  pull_request:
    branches:
      - main
    paths:
      - custom_components/**
      - ".github/workflows/10-hassfest.yml"
  push:
    branches:
      - main
    paths:
      - custom_components/**
      - ".github/workflows/10-hassfest.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    name: Hassfest if custom_components exists
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run hassfest
        if: ${{ hashFiles('custom_components/**/manifest.json') != '' }}
        uses: home-assistant/actions/hassfest@f4ca6f671bd429efb108c0f2fa0ae8af0215986c # master

      - name: Skip
        if: ${{ hashFiles('custom_components/**/manifest.json') == '' }}
        run: echo "No custom integration manifests found; skipping hassfest."
